'                    <input type="text" id="drugSearch" placeholder="Search Master Directory..." oninput="renderMasterList()" style="margin-top: 10px;">',
        '                    <div class="table-wrap" style="margin-top: 10px;">',
        '                        <table>',
        '                            <thead><tr><th>Drug Item</th><th style="text-align:right;">Actions</th></tr></thead>',
        '                            <tbody id="master-drug-table"></tbody>',
        '                        </table>',
        '                    </div>',
        '                    <div class="panel-credit">',
        '                        © 2026 <b>Debanjan Singha</b><br>',
        '                        Enterprise Pharmacy Engine',
        '                    </div>',
        '                </div>',

        '                <!-- PANEL 2: DISPENSE RECORDING ENGINE -->',
        '                <div class="panel">',
        '                    <h2>⚡ Record & Dispense</h2>',
        '                    <select id="dispenseDrugSelect" style="font-weight:650; color:var(--accent);"></select>',
        '                    <div class="qty-grid">',
        '                        <div class="qty-pill" onclick="setQty(1)">1</div>',
        '                        <div class="qty-pill" onclick="setQty(2)">2</div>',
        '                        <div class="qty-pill" onclick="setQty(5)">5</div>',
        '                        <div class="qty-pill" onclick="setQty(10)">10</div>',
        '                    </div>',
        '                    <input type="number" id="dispenseQty" placeholder="Quantity" value="1" min="1">',
        '                    <button class="primary-btn success" onclick="submitDispense()">DISPENSE NOW</button>',
        '                    <hr style="margin:20px 0; border:0; border-top:1px solid #f1f5f9;">',
        '                    <h2>📊 Live Reports & Export</h2>',
        '                    <button class="primary-btn" onclick="exportExcel()" style="margin-bottom:8px;">Export Excel Report</button>',
        '                    <button class="primary-btn warning" onclick="exportPDF()" style="margin-bottom:8px;">Generate Official PDF Report</button>',
        '                    <button class="primary-btn danger" onclick="clearZoneTotals()">Clear Zone Totals</button>',
        '                </div>',

        '                <!-- PANEL 3: REALTIME CUMULATIVE INVENTORY -->',
        '                <div class="panel">',
        '                    <h2>📋 Cumulative Zone Ledger</h2>',
        '                    <input type="text" id="ledgerSearch" placeholder="Search cumulative inventory..." oninput="renderCumulativeLedger()" style="margin-bottom: 10px;">',
        '                    <div class="table-wrap">',
        '                        <table>',
        '                            <thead><tr><th>Drug Name</th><th>Total Dispensed</th><th style="text-align:right;">Quick Edit</th></tr></thead>',
        '                            <tbody id="cumulative-ledger-table"></tbody>',
        '                      </table>',
        '                    </div>',
        '                    <br>',
        '                    <h2>📜 Realtime Transaction Feed</h2>',
        '                    <div class="table-wrap" style="max-height: 220px;">',
        '                        <table>',
        '                            <thead><tr><th>Time</th><th>Drug</th><th>Qty</th><th>By</th></tr></thead>',
        '                            <tbody id="dispense-history-table"></tbody>',
        '                        </table>',
        '                </div>',
        '            </div>',
        '        </div>',
        '    </div>',
        '</div>',

        '<!-- MODAL DIALOGS -->',
        '<div id="modal-container"></div>',

        '<script>',
        'let authToken = localStorage.getItem("rx_token") || "";',
        'let currentUserRole = localStorage.getItem("rx_role") || "";',
        'let currentUsername = localStorage.getItem("rx_user") || "";',
        'let currentPhone = localStorage.getItem("rx_phone") || "";',
        'let userZonesList = JSON.parse(localStorage.getItem("rx_zones") || "[]");',
        'let activeZone = localStorage.getItem("rx_active_zone") || "";',
        'let masterDrugsCache = [];',
        'let dispenseHistoryCache = [];',
        'let syncTimer = null;',

        'window.onload = function() {',
        '    if (authToken) {',
        '        verifySessionAndBootstrap();',
        '    }',
        '};',

        'async function apiCall(endpoint, method = "GET", data = null) {',
        '    const headers = {',
        '        "Content-Type": "application/json",',
        '        "Authorization": "Bearer " + authToken',
        '    };',
        '    const options = { method, headers };',
        '    if (data) options.body = JSON.stringify(data);',
        '    try {',
        '        const res = await fetch(endpoint, options);',
        '        if (res.status === 401 || res.status === 403) {',
        '            handleLogout();',
        '            return null;',
        '        }',
        '        return await res.json();',
        '    } catch (e) {',
        '        console.error("API Error:", e);',
        '        return null;',
        '    }',
        '}',

        'async function handleLogin() {',
        '    const u = document.getElementById("login-username").value.trim();',
        '    const p = document.getElementById("login-password").value;',
        '    const errEl = document.getElementById("login-error");',
        '    errEl.innerText = "";',
        '    if (!u || !p) { errEl.innerText = "Please provide username and password."; return; }',
        '    try {',
        '        const res = await fetch("/api/login", {',
        '            method: "POST",',
        '            headers: { "Content-Type": "application/json" },',
        '            body: JSON.stringify({ username: u, password: p })',
        '        });',
        '        const data = await res.json();',
        '        if (!res.ok) {',
        '            errEl.innerText = data.error || "Authentication failed.";',
        '            return;',
        '        }',
        '        authToken = data.token;',
        '        currentUserRole = data.role;',
        '        currentUsername = data.username;',
        '        currentPhone = data.phone;',
        '        userZonesList = data.zones;',
        '        localStorage.setItem("rx_token", authToken);',
        '        localStorage.setItem("rx_role", currentUserRole);',
        '        localStorage.setItem("rx_user", currentUsername);',
        '        localStorage.setItem("rx_phone", currentPhone);',
        '        localStorage.setItem("rx_zones", JSON.stringify(userZonesList));',
        '        if (userZonesList.length > 0) {',
        '            activeZone = userZonesList[0];',
        '            localStorage.setItem("rx_active_zone", activeZone);',
        '        }',
        '        verifySessionAndBootstrap();',
        '    } catch (e) {',
        '        errEl.innerText = "Server connection error.";',
        '    }',
        '}',

        'async function handleLogout() {',
        '    if (authToken) {',
        '        await apiCall("/api/logout", "POST", { zone: activeZone });',
        '    }',
        '    localStorage.clear();',
        '    authToken = "";',
        '    if (syncTimer) clearInterval(syncTimer);',
        '    document.getElementById("login-screen").classList.remove("hidden");',
        '    document.getElementById("app-screen").classList.add("hidden");',
        '}',

        'async function verifySessionAndBootstrap() {',
        '    document.getElementById("login-screen").classList.add("hidden");',
        '    document.getElementById("app-screen").classList.remove("hidden");',
        '    document.getElementById("role-display").innerText = currentUserRole;',
        '',
        '    if (currentUserRole === "ADMIN") {',
        '        document.getElementById("admin-view").classList.remove("hidden");',
        '        document.getElementById("user-view").classList.add("hidden");',
        '        document.getElementById("user-zone-picker-wrap").style.display = "block";',
        '        document.getElementById("single-zone-badge-wrap").style.display = "none";',
        '        await loadAdminDashboardData();',
        '    } else {',
        '        document.getElementById("admin-view").classList.add("hidden");',
        '        document.getElementById("user-view").classList.remove("hidden");',
        '        if (userZonesList.length > 1) {',
        '            document.getElementById("user-zone-picker-wrap").style.display = "block";',
        '            document.getElementById("single-zone-badge-wrap").style.display = "none";',
        '            populateZonePicker("user-zone-select");',
        '        } else {',
        '            document.getElementById("user-zone-picker-wrap").style.display = "none";',
        '            document.getElementById("single-zone-badge-wrap").style.display = "block";',
        '            document.getElementById("single-zone-name").innerText = activeZone || userZonesList[0] || "DEFAULT";',
        '            if (!activeZone && userZonesList.length > 0) activeZone = userZonesList[0];',
        '        }',
        '        await refreshEngineData();',
        '        if (syncTimer) clearInterval(syncTimer);',
        '        syncTimer = setInterval(refreshEngineData, 2000);',
        '    }',
        '}',

        'async function loadAdminDashboardData() {',
        '    const zones = await apiCall("/api/zones");',
        '    if (zones) {',
        '        const sel = document.getElementById("admin-import-zone");',
        '        sel.innerHTML = \'<option value="">-- Select Target Zone --</option>\';',
        '        zones.forEach(z => {',
        '            sel.innerHTML += `<option value="${z}">${z}</option>`;',
        '        });',
        '        renderZoneCheckboxes(zones);',
        '    }',
        '    const users = await apiCall("/api/users");',
        '    if (users) {',
        '        let html = "";',
        '        users.forEach(u => {',
        '            html += `<tr>',
        '                <td><b>${u.username}</b></td>',
        '                <td>${u.phone}</td>',
        '                <td><span class="badge">${u.zones.join(", ")}</span></td>',
        '                <td>${u.status === 1 ? "<span style=\\\'color:var(--success); font-weight:bold;\\\'>Active</span>" : "<span style=\\\'color:var(--danger); font-weight:bold;\\\'>Disabled</span>"}</td>',
        '                <td>',
        '                    <button class="action-link" onclick="toggleUserStatus(${u.id}, ${u.status})">${u.status === 1 ? "Disable" : "Enable"}</button> | ',
        '                    <button class="action-link" style="color:var(--danger);" onclick="deleteUser(${u.id})">Delete</button>',
        '                </td>',
        '            </tr>`;',
        '        });',
        '        document.getElementById("users-table").innerHTML = html;',
        '    }',
        '    const activity = await apiCall("/api/admin/activity-logs");',
        '    if (activity) {',
        '        let html = "";',
        '        activity.forEach(a => {',
        '            html += `<tr><td>${a.timestamp}</td><td><b>${a.username}</b></td><td>${a.phone}</td><td><span class="badge">${a.action}</span></td></tr>`;',
        '        });',
        '        document.getElementById("activity-table").innerHTML = html;',
        '    }',
        '    const audit = await apiCall("/api/admin/audit-logs");',
        '    if (audit) {',
        '        let html = "";',
        '        audit.forEach(a => {',
        '            html += `<tr><td>${a.timestamp}</td><td><b>${a.username}</b></td><td>${a.phone}</td><td>${a.zone}</td><td><span class="badge">${a.action}</span></td></tr>`;',
        '        });',
        '        document.getElementById("audit-table").innerHTML = html;',
        '    }',
        '}',

        'function renderZoneCheckboxes(zones) {',
        '    const container = document.getElementById("zone-checkbox-container");',
        '    let html = "";',
        '    zones.forEach(z => {',
        '        html += `<label class="zone-checkbox-item"><input type="checkbox" value="${z}" name="newUserZone"> ${z}</label>`;',
        '    });',
        '    container.innerHTML = html;',
        '}',

        'async function registerNewZone() {',
        '    const zName = document.getElementById("new-zone-input").value.trim();',
        '    if (!zName) return;',
        '    const res = await apiCall("/api/zones", "POST", { zone_name: zName });',
        '    if (res) {',
        '        document.getElementById("new-zone-input").value = "";',
        '        loadAdminDashboardData();',
        '    }',
        '}',

        'async function createUser() {',
        '    const name = document.getElementById("nu-name").value.trim();',
        '    const phone = document.getElementById("nu-phone").value.trim();',
        '    const pass = document.getElementById("nu-pass").value;',
        '    const checkboxes = document.querySelectorAll("input[name=\\\'newUserZone\\\']:checked");',
        '    const zones = Array.from(checkboxes).map(cb => cb.value);',
        '    if (!name || !phone || !pass || zones.length === 0) {',
        '        alert("Please fill all details and select at least one zone.");',
        '        return;',
        '    }',
        '    const res = await apiCall("/api/users", "POST", { username: name, phone, password: pass, zones });',
        '    if (res) {',
        '        alert(res.message || "User created.");',
        '        document.getElementById("nu-name").value = "";',
        '        document.getElementById("nu-phone").value = "";',
        '        document.getElementById("nu-pass").value = "";',
        '        loadAdminDashboardData();',
        '    }',
        '}',

        'async function toggleUserStatus(id, currentStatus) {',
        '    const newStatus = currentStatus === 1 ? 0 : 1;',
        '    await apiCall(`/api/users/${id}/status`, "PUT", { status: newStatus });',
        '    loadAdminDashboardData();',
        '}',

        'async function deleteUser(id) {',
        '    if (!confirm("Permanently delete this user account?")) return;',
        '    await apiCall(`/api/users/${id}`, "DELETE");',
        '    loadAdminDashboardData();',
        '}',

        'async function updateAdminProfile() {',
        '    const u = document.getElementById("admin-new-user").value.trim();',
        '    const p = document.getElementById("admin-new-pass").value;',
        '    if (!u || !p) { alert("Provide both new username and password."); return; }',
        '    const res = await apiCall("/api/admin/profile", "PUT", { newUsername: u, newPassword: p });',
        '    if (res) {',
        '        alert(res.message);',
        '        handleLogout();',
        '    }',
        '}',

        'function populateZonePicker(selectId) {',
        '    const sel = document.getElementById(selectId);',
        '    let html = "";',
        '    userZonesList.forEach(z => {',
        '        html += `<option value="${z}" ${z === activeZone ? "selected" : ""}>${z}</option>`;',
        '    });',
        '    sel.innerHTML = html;',
        '}',

        'async function switchZone() {',
        '    const sel = document.getElementById("user-zone-select");',
        '    activeZone = sel.value;',
        '    localStorage.setItem("rx_active_zone", activeZone);',
        '    await refreshEngineData();',
        '}',

        'async function refreshEngineData() {',
        '    if (!activeZone) activeZone = userZonesList[0] || "DEFAULT";',
        '    masterDrugsCache = await apiCall(`/api/master-drugs?zone=${encodeURIComponent(activeZone)}`) || [];',
        '    dispenseHistoryCache = await apiCall(`/api/dispense/sync?zone=${encodeURIComponent(activeZone)}`) || [];',
        '    renderMasterList();',
        '    renderDispenseDropdown();',
        '    renderCumulativeLedger();',
        '    renderDispenseHistory();',
        '}',

        'function renderMasterList() {',
        '    const query = (document.getElementById("drugSearch").value || "").toLowerCase();',
        '    let html = "";',
        '    masterDrugsCache.forEach(d => {',
        '        if (!query || d.toLowerCase().includes(query)) {',
        '            html += `<tr>',
        '                <td><b>${d}</b></td>',
        '                <td style="text-align:right;">',
        '                    <button class="action-link" onclick="renameDrugPrompt(\\\x27${d}\\\x27)">Rename</button> | ',
        '                    <button class="action-link" style="color:var(--danger);" onclick="deleteDrug(\\\x27${d}\\\x27)">Remove</button>',
        '                </td>',
        '            </tr>`;',
        '        }',
        '    });',
        '    document.getElementById("master-drug-table").innerHTML = html;',
        '}',

        'function renderDispenseDropdown() {',
        '    const sel = document.getElementById("dispenseDrugSelect");',
        '    let html = "";',
        '    masterDrugsCache.forEach(d => {',
        '        html += `<option value="${d}">${d}</option>`;',
        '    });',
        '    sel.innerHTML = html;',
        '}',

        'function calculateTotalsMap() {',
        '    const map = {};',
        '    dispenseHistoryCache.forEach(item => {',
        '        const name = (item.drug_name || "").toUpperCase();',
        '        map[name] = (map[name] || 0) + (parseInt(item.qty) || 0);',
        '    });',
        '    return map;',
        '}',

        'function renderCumulativeLedger() {',
        '    const query = (document.getElementById("ledgerSearch").value || "").toLowerCase();',
        '    const totals = calculateTotalsMap();',
        '    let html = "";',
        '    masterDrugsCache.forEach(d => {',
        '        const qty = totals[d] || 0;',
        '        if (!query || d.toLowerCase().includes(query)) {',
        '            html += `<tr>',
        '                <td><b>${d}</b></td>',
        '                <td><span class="badge" style="background:#e6fffa; color:#234e52; font-size:13px;">${qty}</span></td>',
        '                <td style="text-align:right;">',
        '                    <button class="action-link" onclick="adjustCumulativePrompt(\\\x27${d}\\\x27, ${qty})">Edit Qty</button>',
        '                </td>',
        '            </tr>`;',
        '        }',
        '    });',
        '    document.getElementById("cumulative-ledger-table").innerHTML = html;',
        '}',

        'function renderDispenseHistory() {',
        '    let html = "";',
        '    dispenseHistoryCache.slice(0, 50).forEach(item => {',
        '        html += `<tr>',
        '            <td>${item.timestamp ? item.timestamp.split(" ")[1] || item.timestamp : ""}</td>',
        '            <td><b>${item.drug_name}</b></td>',
        '            <td>+${item.qty}</td>',
        '            <td style="color:var(--text-muted); font-size:11px;">${item.entered_by}</td>',
        '        </tr>`;',
        '    });',
        '    document.getElementById("dispense-history-table").innerHTML = html;',
        '}',

        'async function registerDrug() {',
        '    const nameInput = document.getElementById("newDrugName");',
        '    const name = nameInput.value.trim();',
        '    if (!name) return;',
        '    await apiCall("/api/master-drugs", "POST", { zone: activeZone, drug_name: name });',
        '    nameInput.value = "";',
        '    await refreshEngineData();',
        '}',

        'async function deleteDrug(dName) {',
        '    if (!confirm(`Remove ${dName} from master directory?`)) return;',
        '    await apiCall("/api/master-drugs", "DELETE", { zone: activeZone, drug_name: dName });',
        '    await refreshEngineData();',
        '}',

        'async function renameDrugPrompt(oldName) {',
        '    const newName = prompt(`Rename drug "${oldName}" to:`, oldName);',
        '    if (!newName || newName.trim() === oldName) return;',
        '    await apiCall("/api/master-drugs/rename", "PUT", { zone: activeZone, oldName, newName });',
        '    await refreshEngineData();',
        '}',

        'async function adjustCumulativePrompt(dName, currentQty) {',
        '    const val = prompt(`Set total cumulative quantity for "${dName}":`, currentQty);',
        '    if (val === null) return;',
        '    const newQty = parseInt(val);',
        '    if (isNaN(newQty) || newQty < 0) { alert("Invalid quantity value."); return; }',
        '    await apiCall("/api/dispense/adjust-cumulative", "PUT", { zone: activeZone, drug_name: dName, new_qty: newQty });',
        '    await refreshEngineData();',
        '}',

        'function setQty(val) {',
        '    document.getElementById("dispenseQty").value = val;',
        '}',

        'async function submitDispense() {',
        '    const drug_name = document.getElementById("dispenseDrugSelect").value;',
        '    const qty = parseInt(document.getElementById("dispenseQty").value);',
        '    if (!drug_name || isNaN(qty) || qty <= 0) {',
        '        alert("Select a valid drug and quantity.");',
        '        return;',
        '    }',
        '    await apiCall("/api/dispense", "POST", { zone: activeZone, drug_name, qty });',
        '    await refreshEngineData();',
        '}',

        'async function clearZoneTotals() {',
        '    if (!confirm(`Clear all dispense records for zone "${activeZone}"?`)) return;',
        '    await apiCall("/api/dispense/clear/all", "DELETE", { zone: activeZone });',
        '    await refreshEngineData();',
        '}',

        'async function processImport(type, mode) {',
        '    const zone = document.getElementById("admin-import-zone").value;',
        '    const fileInput = document.getElementById("admin-file-import");',
        '    if (!zone) { alert("Please select a target zone."); return; }',
        '    if (!fileInput.files.length) { alert("Please choose a file to import."); return; }',
        '',
        '    const file = fileInput.files[0];',
        '    const reader = new FileReader();',
        '    reader.onload = async function(e) {',
        '        try {',
        '            let drugsData = [];',
        '            if (file.name.endsWith(".json")) {',
        '                drugsData = JSON.parse(e.target.result);',
        '            } else {',
        '                const data = new Uint8Array(e.target.result);',
        '                const workbook = XLSX.read(data, { type: "array" });',
        '                const firstSheetName = workbook.SheetNames[0];',
        '                const worksheet = workbook.Sheets[firstSheetName];',
        '                drugsData = XLSX.utils.sheet_to_json(worksheet, { header: 1 });',
        '            }',
        '            const res = await apiCall("/api/master-drugs/import", "POST", {',
        '                zone,',
        '                mode,',
        '                drugs: drugsData',
        '            });',
        '            if (res) {',
        '                alert(res.message || "Import completed successfully.");',
        '                fileInput.value = "";',
        '            }',
        '        } catch (err) {',
        '            alert("Failed to parse file: " + err.message);',
        '        }',
        '    };',
        '    if (file.name.endsWith(".json")) {',
        '        reader.readAsText(file);',
        '    } else {',
        '        reader.readAsArrayBuffer(file);',
        '    }',
        '}',

        'function exportExcel() {',
        '    const totals = calculateTotalsMap();',
        '    const rows = masterDrugsCache.map(d => ({',
        '        "Drug Name": d,',
        '        "Total Dispensed": totals[d] || 0,',
        '        "Zone": activeZone',
        '    }));',
        '    const worksheet = XLSX.utils.json_to_sheet(rows);',
        '    const workbook = XLSX.utils.book_new();',
        '    XLSX.utils.book_append_sheet(workbook, worksheet, "Inventory Summary");',
        '    XLSX.writeFile(workbook, `RxMediSync_${activeZone}_Inventory.xlsx`);',
        '}',

        'function exportPDF() {',
        '    const { jsPDF } = window.jspdf;',
        '    const doc = new jsPDF();',
        '    const totals = calculateTotalsMap();',
        '',
        '    doc.setFontSize(18);',
        '    doc.setTextColor(27, 38, 59);',
        '    doc.text("RxMEDISYNC PRO | OFFICIAL INVENTORY REPORT", 14, 20);',
        '',
        '    doc.setFontSize(11);',
        '    doc.setTextColor(100, 100, 100);',
        '    doc.text(`Zone: ${activeZone} | Generated On: ${new Date().toLocaleString()}`, 14, 28);',
        '    doc.text(`Lead System Architect: Debanjan Singha`, 14, 34);',
        '',
        '    const tableData = masterDrugsCache.map(d => [d, totals[d] || 0]);',
        '    doc.autoTable({',
        '        startY: 42,',
        '        head: [["Drug Name", "Total Dispensed"]],',
        '        body: tableData,',
        '        theme: "grid",',
        '        headStyles: { fillColor: [27, 38, 59] }',
        '    });',
        '',
        '    doc.save(`RxMediSync_${activeZone}_Report.pdf`);',
        '}',
        '</script>',
        '</body>',
        '</html>'
    ];

    res.send(htmlLines.join('\n'));
});

// Start High Concurrency Server Engine
app.listen(PORT, () => {
    console.log(`RxMediSync Pro Enterprise Server active on port ${PORT}`);
});
