// ... [Continuing seamlessly from the truncated backend string in route /]
        '                        <input type="text" id="drugSearch" placeholder="Search master drugs..." oninput="renderMasterDrugs()" style="margin-top:10px;">',
        '                        <div class="table-wrap" style="margin-top:10px;">',
        '                            <table id="master-drugs-table">',
        '                                <thead><tr><th>Drug Name</th><th>Actions</th></tr></thead>',
        '                                <tbody id="master-tbody"></tbody>',
        '                            </table>',
        '                        </div>',
        '                    </div>',

        '                    <!-- PANEL 2: DISPENSE / RECORD -->',
        '                    <div class="panel">',
        '                        <h2>⚡ Express Dispense Engine</h2>',
        '                        <select id="dispenseDrugSelect" onchange="updateSelectedDrugState()"><option value="">-- Select Drug --</option></select>',
        '                        <div class="qty-grid">',
        '                            <div class="qty-pill" onclick="setDispenseQty(1)">1</div>',
        '                            <div class="qty-pill" onclick="setDispenseQty(5)">5</div>',
        '                            <div class="qty-pill" onclick="setDispenseQty(10)">10</div>',
        '                            <div class="qty-pill" onclick="setDispenseQty(20)">20</div>',
        '                      </div>',
        '                        <input type="number" id="dispenseQty" placeholder="Quantity" value="1" onkeydown="if(event.key===\'Enter\') submitDispense()">',
        '                        <button class="primary-btn success" onclick="submitDispense()">RECORD DISPENSE</button>',
        '                        <div style="margin-top:20px; border-top:1px solid #f1f5f9; padding-top:15px;">',
        '                            <h2 style="margin-bottom:10px;">📊 Zone Quick Export</h2>',
        '                            <div class="flex">',
        '                                <button onclick="exportReport(\'excel\')" class="primary-btn success">Export Excel</button>',
        '                                <button onclick="exportReport(\'pdf\')" class="primary-btn danger">Export PDF</button>',
        '                          </div>',
        '                          <button onclick="clearAllZoneData()" class="primary-btn danger" style="margin-top:10px; background:#4a5568;">Clear Zone Totals</button>',
        '                      </div>',
        '                    </div>',

        '                    <!-- PANEL 3: LIVE ZONE LEDGER -->',
        '                    <div class="panel">',
        '                        <h2>📋 Realtime Transaction Ledger</h2>',
        '                        <input type="text" id="ledgerSearch" placeholder="Filter ledger records..." oninput="renderLedger()" style="margin-bottom:10px;">',
        '                        <div class="table-wrap">',
        '                            <table>',
        '                                <thead><tr><th>Time</th><th>Drug Name</th><th>Qty</th><th>Operator</th><th>Actions</th></tr></thead>',
        '                                <tbody id="ledger-tbody"></tbody>',
        '                          </table>',
        '                      </div>',
        '                    </div>',
        '                </div>',
        '            </div>',
        '        </div>',

        '        <!-- CLIENT-SIDE JAVASCRIPT ENGINE -->',
        '        <script>',
        '            let authToken = localStorage.getItem("rx_token") || "";',
        '            let currentUserRole = localStorage.getItem("rx_role") || "";',
        '            let currentUsername = localStorage.getItem("rx_user") || "";',
        '            let userZonesList = JSON.parse(localStorage.getItem("rx_zones") || "[]");',
        '            let activeZone = localStorage.getItem("rx_active_zone") || "";',
        '            let masterDrugs = [];',
        '            let dispensesLog = [];',
        '            let autoSyncInterval = null;',

        '            window.onload = function() {',
        '                if (authToken) {',
        '                    bootAppUI();',
        '                }',
        '            };',

        '            async function handleLogin() {',
        '                const u = document.getElementById("login-username").value.trim();',
        '                const p = document.getElementById("login-password").value.trim();',
        '                const errDiv = document.getElementById("login-error");',
        '                errDiv.innerText = "";',

        '                try {',
        '                    const res = await fetch("/api/login", {',
        '                        method: "POST",',
        '                        headers: { "Content-Type": "application/json" },',
        '                        body: JSON.stringify({ username: u, password: p })',
        '                    });',
        '                    const data = await res.json();',
        '                    if (!res.ok) throw new Error(data.error || "Login failed");',

        '                    authToken = data.token;',
        '                    currentUserRole = data.role;',
        '                    currentUsername = data.username;',
        '                    userZonesList = data.zones;',
        '                    activeZone = userZonesList.length > 0 ? userZonesList[0] : "";',

        '                    localStorage.setItem("rx_token", authToken);',
        '                    localStorage.setItem("rx_role", currentUserRole);',
        '                    localStorage.setItem("rx_user", currentUsername);',
        '                    localStorage.setItem("rx_zones", JSON.stringify(userZonesList));',
        '                    localStorage.setItem("rx_active_zone", activeZone);',

        '                    bootAppUI();',
        '                } catch (e) {',
        '                    errDiv.innerText = e.message;',
        '                }',
        '        }',

        '        async function handleLogout() {',
        '            try {',
        '                await fetch("/api/logout", {',
        '                    method: "POST",',
        '                    headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                    body: JSON.stringify({ zone: activeZone })',
        '                });',
        '            } catch(e) {}',
        '            localStorage.clear();',
        '            location.reload();',
        '        }',

        '        function bootAppUI() {',
        '            document.getElementById("login-screen").classList.add("hidden");',
        '            document.getElementById("app-screen").classList.remove("hidden");',
        '            document.getElementById("role-display").innerText = currentUserRole + " (" + currentUsername + ")";',

        '            if (currentUserRole === "ADMIN") {',
        '                document.getElementById("admin-view").classList.remove("hidden");',
        '                loadAdminRegistryData();',
        '            } else {',
        '                document.getElementById("user-view").classList.remove("hidden");',
        '            }',

        '            setupZoneSelectors();',
        '            fetchAllData();',

        '            if (autoSyncInterval) clearInterval(autoSyncInterval);',
        '            autoSyncInterval = setInterval(fetchAllData, 2000);',
        '        }',

        '        async function setupZoneSelectors() {',
        '            try {',
        '                const res = await fetch("/api/zones", { headers: { "Authorization": "Bearer " + authToken } });',
        '                const zones = await res.json();',
        '                if (currentUserRole === "ADMIN") {',
        '                    // Admin can inspect any zone',
        '                    let allZones = zones;',
        '                    const picker = document.getElementById("user-zone-select");',
        '                    picker.innerHTML = "";',
        '                    allZones.forEach(z => {',
        '                        let opt = document.createElement("option");',
        '                        opt.value = z;',
        '                        opt.innerText = z;',
        '                        if (z === activeZone) opt.selected = true;',
        '                        picker.appendChild(opt);',
        '                    });',
        '                    document.getElementById("user-zone-picker-wrap").style.display = "block";',
        '                    document.getElementById("single-zone-badge-wrap").style.display = "none";',
        '                } else {',
        '                    if (userZonesList.length > 1) {',
        '                        const picker = document.getElementById("user-zone-select");',
        '                        picker.innerHTML = "";',
        '                        userZonesList.forEach(z => {',
        '                            let opt = document.createElement("option");',
        '                            opt.value = z;',
        '                            opt.innerText = z;',
        '                            if (z === activeZone) opt.selected = true;',
        '                            picker.appendChild(opt);',
        '                        });',
        '                        document.getElementById("user-zone-picker-wrap").style.display = "block";',
        '                        document.getElementById("single-zone-badge-wrap").style.display = "none";',
        '                    } else {',
        '                        document.getElementById("user-zone-picker-wrap").style.display = "none";',
        '                        document.getElementById("single-zone-badge-wrap").style.display = "block";',
        '                        document.getElementById("single-zone-name").innerText = activeZone || "DEFAULT";',
        '                    }',
        '                }',
        '            } catch(e) {}',
        '        }',

        '        function switchZone() {',
        '            const picker = document.getElementById("user-zone-select");',
        '            if (picker) {',
        '                activeZone = picker.value;',
        '                localStorage.setItem("rx_active_zone", activeZone);',
        '                fetchAllData();',
        '            }',
        '        }',

        '        async function fetchAllData() {',
        '            if (!activeZone) return;',
        '            try {',
        '                // Fetch Master Drugs',
        '                const resDrugs = await fetch("/api/master-drugs?zone=" + encodeURIComponent(activeZone), {',
        '                    headers: { "Authorization": "Bearer " + authToken }',
        '                });',
        '                if (resDrugs.ok) {',
        '                    masterDrugs = await resDrugs.json();',
        '                    renderMasterDrugs();',
        '                    populateDrugDropdown();',
        '                }',

        '                // Fetch Dispense Sync',
        '                const resDisp = await fetch("/api/dispense/sync?zone=" + encodeURIComponent(activeZone), {',
        '                    headers: { "Authorization": "Bearer " + authToken }',
        '                });',
        '                if (resDisp.ok) {',
        '                    dispensesLog = await resDisp.json();',
        '                    renderLedger();',
        '                }',

        '                if (currentUserRole === "ADMIN") {',
        '                    loadAdminRegistryData();',
        '                }',
        '            } catch(e) {}',
        '        }',

        '        // Master Drug Operations',
        '        async function registerDrug() {',
        '            const input = document.getElementById("newDrugName");',
        '            const dName = input.value.trim();',
        '            if (!dName) return;',
        '            await fetch("/api/master-drugs", {',
        '                method: "POST",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ zone: activeZone, drug_name: dName })',
        '            });',
        '            input.value = "";',
        '            fetchAllData();',
        '        }',

        '        async function deleteDrug(dName) {',
        '            if (!confirm("Remove " + dName + " from master directory?")) return;',
        '            await fetch("/api/master-drugs", {',
        '                method: "DELETE",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ zone: activeZone, drug_name: dName })',
        '            });',
        '            fetchAllData();',
        '        }',

        '        async function renameDrugPrompt(oldName) {',
        '            const newName = prompt("Enter corrected drug name:", oldName);',
        '            if (!newName || newName.trim() === oldName) return;',
        '            await fetch("/api/master-drugs/rename", {',
        '                method: "PUT",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ zone: activeZone, oldName: oldName, newName: newName })',
        '            });',
        '            fetchAllData();',
        '        }',

        '        function renderMasterDrugs() {',
        '            const filter = (document.getElementById("drugSearch").value || "").toUpperCase();',
        '            const tbody = document.getElementById("master-tbody");',
        '            tbody.innerHTML = "";',

        '            masterDrugs.filter(d => d.includes(filter)).forEach(d => {',
        '                let tr = document.createElement("tr");',
        '                tr.innerHTML = `<td><b>${d}</b></td><td>' +',
        '                    `<button class="action-link" onclick="renameDrugPrompt(\'${d}\')">Rename</button> | ` +',
        '                    `<button class="action-link" style="color:var(--danger)" onclick="deleteDrug(\'${d}\')">Remove</button>` +',
        '                    `</td>`;',
        '                tbody.appendChild(tr);',
        '            });',
        '        }',

        '        function populateDrugDropdown() {',
        '            const select = document.getElementById("dispenseDrugSelect");',
        '            const currentVal = select.value;',
        '            select.innerHTML = \'<option value="">-- Select Drug --</option>\';',
        '            masterDrugs.forEach(d => {',
        '                let opt = document.createElement("option");',
        '                opt.value = d;',
        '                opt.innerText = d;',
        '                if (d === currentVal) opt.selected = true;',
        '                select.appendChild(opt);',
        '            });',
        '        }',

        '        function setDispenseQty(q) {',
        '            document.getElementById("dispenseQty").value = q;',
        '        }',

        '        async function submitDispense() {',
        '            const drugName = document.getElementById("dispenseDrugSelect").value;',
        '            const qty = parseInt(document.getElementById("dispenseQty").value);',
        '            if (!drugName) { alert("Please select a drug."); return; }',
        '            if (isNaN(qty) || qty <= 0) { alert("Please enter valid quantity."); return; }',

        '            await fetch("/api/dispense", {',
        '                method: "POST",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ zone: activeZone, drug_name: drugName, qty: qty })',
        '            });',

        '            document.getElementById("dispenseQty").value = "1";',
        '            fetchAllData();',
        '        }',

        '        function renderLedger() {',
        '            const filter = (document.getElementById("ledgerSearch").value || "").toUpperCase();',
        '            const tbody = document.getElementById("ledger-tbody");',
        '            tbody.innerHTML = "";',

        '            dispensesLog.filter(item => String(item.drug_name).toUpperCase().includes(filter) || String(item.entered_by).toUpperCase().includes(filter)).forEach(item => {',
        '                let tr = document.createElement("tr");',
        '                tr.innerHTML = `<td style="font-size:11px; color:var(--text-muted);">${item.timestamp}</td>` +' +',
        '                    `<td><b>${item.drug_name}</b></td>` +' +',
        '                    `<td><span class="badge">${item.qty}</span></td>` +' +',
        '                    `<td style="font-size:12px;">${item.entered_by}</td>` +' +',
        '                    `<td><button class="action-link" style="color:var(--danger)" onclick="deleteDispenseRecord(${item.id})">Delete</button></td>`;',
        '                tbody.appendChild(tr);',
        '            });',
        '        }',

        '        async function deleteDispenseRecord(id) {',
        '            if (!confirm("Delete transaction record?")) return;',
        '            await fetch("/api/dispense/" + id, {',
        '                method: "DELETE",',
        '                headers: { "Authorization": "Bearer " + authToken }',
        '            });',
        '            fetchAllData();',
        '        }',

        '        async function clearAllZoneData() {',
        '            if (!confirm("WARNING: Clear all transactions for zone " + activeZone + "?")) return;',
        '            await fetch("/api/dispense/clear/all", {',
        '                method: "DELETE",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ zone: activeZone })',
        '            });',
        '            fetchAllData();',
        '        }',

        '        // Admin Management Functions',
        '        async function loadAdminRegistryData() {',
        '            try {',
        '                // Fetch Zones',
        '                const resZ = await fetch("/api/zones", { headers: { "Authorization": "Bearer " + authToken } });',
        '                const zones = await resZ.json();',
        '                const zoneContainer = document.getElementById("zone-checkbox-container");',
        '                zoneContainer.innerHTML = "";',
        '                zones.forEach(z => {',
        '                    let lbl = document.createElement("label");',
        '                    lbl.className = "zone-checkbox-item";',
        '                    lbl.innerHTML = `<input type="checkbox" value="${z}" name="admin-user-zone"> ${z}`;',
        '                    zoneContainer.appendChild(lbl);',
        '                });',

        '                const importSelect = document.getElementById("admin-import-zone");',
        '                importSelect.innerHTML = \'<option value="">-- Select Target Zone --</option>\';',
        '                zones.forEach(z => {',
        '                    let opt = document.createElement("option");',
        '                    opt.value = z;',
        '                    opt.innerText = z;',
        '                    importSelect.appendChild(opt);',
        '                });',

        '                // Fetch Users',
        '                const resU = await fetch("/api/users", { headers: { "Authorization": "Bearer " + authToken } });',
        '                const users = await resU.json();',
        '                const uTbody = document.getElementById("users-table");',
        '                uTbody.innerHTML = "";',
        '                users.forEach(u => {',
        '                    let tr = document.createElement("tr");',
        '                    tr.innerHTML = `<td><b>${u.username}</b></td>` +' +',
        '                        `<td>${u.phone}</td>` +' +',
        '                        `<td><span class="badge">${u.zones.join(", ")}</span></td>` +' +',
        '                        `<td>${u.status === 1 ? "<span style=\'color:var(--success)\'>Active</span>" : "<span style=\'color:var(--danger)\'>Disabled</span>"}</td>` +' +',
        '                        `<td>` +' +',
        '                        `<button class="action-link" onclick="toggleUserStatus(${u.id}, ${u.status === 1 ? 0 : 1})">${u.status === 1 ? "Disable" : "Enable"}</button> | ` +' +',
        '                        `<button class="action-link" style="color:var(--danger)" onclick="deleteUser(${u.id})">Delete</button>` +' +',
        '                        `</td>`;',
        '                    uTbody.appendChild(tr);',
        '                });',

        '                // Fetch Activity Logs',
        '                const resAct = await fetch("/api/admin/activity-logs", { headers: { "Authorization": "Bearer " + authToken } });',
        '                const acts = await resAct.json();',
        '                const actTbody = document.getElementById("activity-table");',
        '                actTbody.innerHTML = "";',
        '                acts.forEach(a => {',
        '                    let tr = document.createElement("tr");',
        '                    tr.innerHTML = `<td style="font-size:11px;">${a.timestamp}</td><td><b>${a.username}</b></td><td>${a.phone}</td><td><span class="badge">${a.action}</span></td>`;',
        '                    actTbody.appendChild(tr);',
        '                });',

        '                // Fetch Audit Logs',
        '                const resAud = await fetch("/api/admin/audit-logs", { headers: { "Authorization": "Bearer " + authToken } });',
        '                const auds = await resAud.json();',
        '                const audTbody = document.getElementById("audit-table");',
        '                audTbody.innerHTML = "";',
        '                auds.forEach(au => {',
        '                    let tr = document.createElement("tr");',
        '                    tr.innerHTML = `<td style="font-size:11px;">${au.timestamp}</td><td><b>${au.username}</b></td><td>${au.phone}</td><td style="font-size:11px;">${au.zone}</td><td><span class="badge">${au.action}</span></td>`;',
        '                    audTbody.appendChild(tr);',
        '                });',
        '            } catch(e) {}',
        '        }',

        '        async function registerNewZone() {',
        '            const zInput = document.getElementById("new-zone-input");',
        '            const zName = zInput.value.trim();',
        '            if (!zName) return;',
        '            await fetch("/api/zones", {',
        '                method: "POST",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ zone_name: zName })',
        '            });',
        '            zInput.value = "";',
        '            loadAdminRegistryData();',
        '        }',

        '        async function createUser() {',
        '            const name = document.getElementById("nu-name").value.trim();',
        '            const phone = document.getElementById("nu-phone").value.trim();',
        '            const pass = document.getElementById("nu-pass").value.trim();',
        '            const checkboxes = document.querySelectorAll("input[name=\'admin-user-zone\']:checked");',
        '            let selectedZones = Array.from(checkboxes).map(cb => cb.value);',

        '            if (!name || !phone || !pass || selectedZones.length === 0) {',
        '                alert("Please provide all credentials and select at least one zone.");',
        '                return;',
        '            }',

        '            const res = await fetch("/api/users", {',
        '                method: "POST",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ username: name, phone: phone, password: pass, zones: selectedZones })',
        '            });',
        '            const data = await res.json();',
        '            if (!res.ok) { alert(data.error); return; }',

        '            document.getElementById("nu-name").value = "";',
        '            document.getElementById("nu-phone").value = "";',
        '            document.getElementById("nu-pass").value = "";',
        '            loadAdminRegistryData();',
        '        }',

        '        async function toggleUserStatus(id, newStatus) {',
        '            await fetch("/api/users/" + id + "/status", {',
        '                method: "PUT",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ status: newStatus })',
        '            });',
        '            loadAdminRegistryData();',
        '        }',

        '        async function deleteUser(id) {',
        '            if (!confirm("Permanently delete user account?")) return;',
        '            await fetch("/api/users/" + id, {',
        '                method: "DELETE",',
        '                headers: { "Authorization": "Bearer " + authToken }',
        '            });',
        '            loadAdminRegistryData();',
        '        }',

        '        async function updateAdminProfile() {',
        '            const u = document.getElementById("admin-new-user").value.trim();',
        '            const p = document.getElementById("admin-new-pass").value.trim();',
        '            if (!u || !p) { alert("Provide new admin username and password."); return; }',
        '            const res = await fetch("/api/admin/profile", {',
        '                method: "PUT",',
        '                headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                body: JSON.stringify({ newUsername: u, newPassword: p })',
        '            });',
        '            const data = await res.json();',
        '            alert(data.message || data.error);',
        '        }',

        '        // Bulk Import Handler',
        '        async function processImport(targetType, mode) {',
        '            const zone = document.getElementById("admin-import-zone").value;',
        '            const fileInput = document.getElementById("admin-file-import");',
        '            if (!zone) { alert("Select target zone for import."); return; }',
        '            if (!fileInput.files.length) { alert("Please select a file to import."); return; }',

        '            const file = fileInput.files[0];',
        '            const reader = new FileReader();',

        '            reader.onload = async function(e) {',
        '                try {',
        '                    let parsedData = [];',
        '                    if (file.name.endsWith(".json")) {',
        '                        parsedData = JSON.parse(e.target.result);',
        '                    } else {',
        '                        const data = new Uint8Array(e.target.result);',
        '                        const workbook = XLSX.read(data, { type: "array" });',
        '                        const firstSheet = workbook.SheetNames[0];',
        '                        parsedData = XLSX.utils.sheet_to_json(workbook.Sheets[firstSheet]);',
        '                    }',

        '                    const res = await fetch("/api/master-drugs/import", {',
        '                        method: "POST",',
        '                        headers: { "Authorization": "Bearer " + authToken, "Content-Type": "application/json" },',
        '                        body: JSON.stringify({ zone: zone, mode: mode, drugs: parsedData })',
        '                    });',
        '                    const result = await res.json();',
        '                    alert(result.message || result.error);',
        '                    fileInput.value = "";',
        '                    fetchAllData();',
        '                } catch (err) {',
        '                    alert("Import parsing error: " + err.message);',
        '                }',
        '            };',

        '            if (file.name.endsWith(".json")) {',
        '                reader.readAsText(file);',
        '            } else {',
        '                reader.readAsArrayBuffer(file);',
        '            }',
        '        }',

        '        // Export Reports',
        '        function exportReport(type) {',
        '            // Aggregate totals by drug name',
        '            let totals = {};',
        '            dispensesLog.forEach(item => {',
        '                let d = item.drug_name;',
        '                totals[d] = (totals[d] || 0) + item.qty;',
        '            });',

        '            let rows = Object.keys(totals).map(d => [d, totals[d]]);',

        '            if (type === "excel") {',
        '                let wsData = [["Drug Name", "Total Dispensed Qty"], ...rows];',
        '                let ws = XLSX.utils.aoa_to_sheet(wsData);',
        '                let wb = XLSX.utils.book_new();',
        '                XLSX.utils.book_append_sheet(wb, ws, "Zone Summary");',
        '                XLSX.writeFile(wb, "RxMediSync_" + activeZone + "_Report.xlsx");',
        '            } else if (type === "pdf") {',
        '                const { jsPDF } = window.jspdf;',
        '                const doc = new jsPDF();',
        '                doc.text("RxMEDISYNC PRO - Zone Report: " + activeZone, 14, 20);',
        '                doc.autoTable({',
        '                    startY: 25,',
        '                    head: [["Drug Name", "Total Dispensed Qty"]],',
        '                    body: rows',
        '                });',
        '                doc.save("RxMediSync_" + activeZone + "_Report.pdf");',
        '            }',
        '        }',
        '    </script>',
        '</body>',
        '</html>'
    ];
    res.send(htmlLines.join('\n'));
});

app.listen(PORT, () => {
    console.log(`RxMediSync Pro Engine running seamlessly on port ${PORT}`);
});
